### ISSUE TITLE
Tab bar visible with full screen videos

### ISSUE THREAD

**Issue by Keith94** [yfdyh000/tabutils#108]
When tab bar is set to left/right/bottom, tabs should not be visible when browser is set to "dom fullscreen mode" such as for full screen YouTube videos. A possible css fix:

``` css
#main-window[inDOMFullscreen] #TabsToolbar {
    visibility: collapse;
}
```
